### ISSUE TITLE
The Host Encoder failed to initialize

### ISSUE THREAD

**Issue by SmokeyBR** [jamesstringerparsec/Easy-GPU-P#9]
Tested with windows 10 21H2 all went well except connecting with parsec

Im getting this error on parsec error 15000 The Host Encoder Failed to Initialize.
im pretty sure all my hardware is compatible, running `Set-VMPartitionableGpu` gives me no output

MB: Asus z97m PLUS
CPU: i5 4440
GPU: AMD RX 580

**Comment by jamesstringerparsec** [comment]
Please check the state of the RX 580 in your virtual machines display adapters section of device manager.  Does it show a yellow triangle? Is it there at all?

**Comment by SmokeyBR** [comment]
![image](https://user-images.githubusercontent.com/19333582/143871809-5206eb4e-f38c-4baf-be19-d4f84b5d2372.png)

seems all good

**Comment by jamesstringerparsec** [comment]
Are you running the most recent drivers for the RX 580?  Make sure you download drivers from AMD.com, rather than using Windows update.

**Comment by SmokeyBR** [comment]
yes most recent drivers installed from amd.com
![image](https://user-images.githubusercontent.com/19333582/144470636-c08190ef-d3ea-407e-aa4f-2c4f5b1eba32.png)
![image](https://user-images.githubusercontent.com/19333582/144470709-6efd1335-41b8-41d0-b5dc-6043d509c0fa.png)

**Comment by igorpdasilvaa** [comment]
@SmokeyBR same here, but i think this is not a problem with this project. I followed another tutorial and falled in the same error. the same tutorial for a gtx 1050 works greatly, so i think the problem is our GPU and the actual state of the GPU-P or the AMD drivers.
I will update here if i get some success on that

**Comment by igorpdasilvaa** [comment]
@SmokeyBR  Maybe this just won't will work on rx 580, look at this link https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/223 
Anyone with a newer Radeon GPU to test ? maybe will work in a newer GPU

**Comment by SmokeyBR** [comment]
i cant be of much help here, im afraid its all to technical for me, that issue seems to be treated as a bug and apparently they did fix it.... so im still hopefull

**Comment by jamesstringerparsec** [comment]
You can test something for me, enable [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview#installation). Then install Parsec from parsec.app/downloads on this Windows Sandbox and tell me if you can connect to this Sandbox using Parsec...It uses the same technology as GPU-P

**Comment by igorpdasilvaa** [comment]
@SmokeyBR In resume i think this is only work in a new generation of radeon GPUs because we have a hardware limitation. if you know someone with a rx 6000 series to make the test and report here if works will be very great. 
@jamesstringerparsec I will try that, in one or two days i report the test here

**Comment by igorpdasilvaa** [comment]
@jamesstringerparsec  got some time here and tested, inside the Windows Sandbox i have the same problem

**Comment by jamesstringerparsec** [comment]
OK, that would suggest there is nothing I can do in this script to fix it, since Windows Sandbox is the official way Microsoft uses GPU-P.  My 5700XT works fine with GPU-P.

**Comment by igorpdasilvaa** [comment]
@jamesstringerparsec you ran into windows 11 right ? i ran into windows 10. I will install 11 here and try again to see if the result is the same ( i think will be the same )

**Comment by Dimantio** [comment]
Having the same issue here with my RX 580, everything works great except Parsec pretty strange.

**Comment by Greennetherking** [comment]
I have the same issue, VM is using Windows 11 and everything seems to work except Parsec and installing drivers.
Trying to install drivers says there is no compatible GPU found and I have the exact same thing in device manager that SmokeyBR has.

**Comment by ItsPapoPlayz** [comment]
I'm also having the same issue, Windows 11 Build 22000.318 (Guest), Windows 10 Build 19044.1415 (Host). I tried installing NVIDIA GPU drivers but it said no compatible hardware.

**Comment by Doge5678** [comment]
same issue with RX-570 tried with the newest driver that released today but still no luck everything works except parsec

**Comment by igorpdasilvaa** [comment]
@ItsPapoPlayz the drivers no need to be installed, will be used the drivers of host OS

@Dimantio @Doge5678  is a hardware limitation :(

**Comment by Zaskmaisonpiege** [comment]
I have the same problem with my Amd radeon R7 370
But with my Gtx 960 Its work flawlessly
I hope someone gonna find a solution for this Btw

**Comment by Doge5678** [comment]
> @ItsPapoPlayz the drivers no need to be installed, will be used the drivers of host OS
> 
> @Dimantio @Doge5678 is a hardware limitation :(

are you sure it is it sounds something like a driver problem

**Comment by PermaFreez** [comment]
I'm having the same problem, I have an rx 570.

**Comment by Vaakmeister** [comment]
It's probably because AMD Polaris GPUs and older do not support hardware encoding in GPU Paravirtualisation mode. If someone can find out a way to fix that, Parsec should work.

It's the final sentence on the project's README.

> AMD Polaris GPUS like the RX 580 do not support hardware video encoding via GPU Paravirtualization at this time.

**Comment by sohcah** [comment]
Encountering the same issue with my Radeon RX570. :(

**Comment by PeterTucker** [comment]
BUMP... not working in R9 280X

**Comment by PeterTucker** [comment]
@jamesstringerparsec or @Vaakmeister , do you know if there is an official list of GPUs from AMD that  support hardware encoding in GPU Paravirtualisation mode? I could not find a list.

**Comment by Vaakmeister** [comment]
I’m no expert but from what I gather don’t expect it to work in any AMD consumer gpu before they started with RDNA architecture (5000 series). As far as I am aware Paravirtualization is still not an officially supported feature even on the newer cards so there probably won’t be an official list for it.

**Comment by KYatoo** [comment]
Same issue on RX6500XT.

**Comment by scaady** [comment]
Same problem with 2080 ti, worked fine up until this point.

**Comment by scaady** [comment]
![image](https://user-images.githubusercontent.com/96739550/166599796-59f183f4-3c90-46ba-b35a-ac78d90fd3a1.png)

**Comment by kalelkenobi** [comment]
Hi there, I'm facing the same issue but I have an RX 6900XT that should support hwvideo encoding via GPU-P in a Windows-VM. I re-run the script multiple times and tried updating/reinstalling AMD Adrenaline and drivers. Is there something else that I can try? Am I missing something?

**Comment by bloodhound255** [comment]
> Hi there, I'm facing the same issue but I have an RX 6900XT that should support hwvideo encoding via GPU-P in a Windows-VM. I re-run the script multiple times and tried updating/reinstalling AMD Adrenaline and drivers. Is there something else that I can try? Am I missing something?

I also have the same issue with a 6900XT and 5900XT CPU. All drivers are up to date, and I ran the script to update the VM drivers. Parsec blackscreens, and gives me this error: https://support.parsec.app/hc/en-us/articles/115002624051

**Comment by Timothy21** [comment]
> > Hi there, I'm facing the same issue but I have an RX 6900XT that should support hwvideo encoding via GPU-P in a Windows-VM. I re-run the script multiple times and tried updating/reinstalling AMD Adrenaline and drivers. Is there something else that I can try? Am I missing something?
> 
> I also have the same issue with a 6900XT and 5900XT CPU. All drivers are up to date, and I ran the script to update the VM drivers. Parsec blackscreens, and gives me this error: https://support.parsec.app/hc/en-us/articles/115002624051

same issue for 6800XT, popped out error info 15000, and the weird thing is when I use Parsec in my actual PC(not VM one), it works perfectly.

**Comment by Timothy21** [comment]
Solution found, my 6800XT driver is 22.7.1, not WHQL 22.5.1, after downgrade drvier to 22.5.1 and upload driver to VM, it works perfectly for Parsec encoder, you guys can try it.

**Comment by sinni800** [comment]
> Solution found, my 6800XT driver is 22.7.1, not WHQL 22.5.1, after downgrade drvier to 22.5.1 and upload driver to VM, it works perfectly for Parsec encoder, you guys can try it.

I hope it's only that WHQL drivers will keep working, but the edge drivers not, and not that the support for the feature is entirely gone after 22.5

**Comment by Timothy21** [comment]
Hope it's just optional driver prob. And another one question, what if my physical PC GPU driver is upgrade to the latest one, but remain the old one in VM,will the VM still work? Or the physical PC and VM must be the same version driver.
> > Solution found, my 6800XT driver is 22.7.1, not WHQL 22.5.1, after downgrade drvier to 22.5.1 and upload driver to VM, it works perfectly for Parsec encoder, you guys can try it.
> 
> 
> 
> I hope it's only that WHQL drivers will keep working, but the edge drivers not, and not that the support for the feature is entirely gone after 22.5

**Comment by SmokeyBR** [comment]
> @SmokeyBR Maybe this just won't will work on rx 580, look at this link [GPUOpen-LibrariesAndSDKs/AMF#223](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/223) Anyone with a newer Radeon GPU to test ? maybe will work in a newer GPU

@igorpdasilvaa i saw the issue you referenced was resolved, did u get a chance and test? there was a couple of drivers updates since then

**Comment by liv3rise** [comment]
Just tested this with my RX 570 and latest driver, still the same issue. The virtual machine starts up, the GPU is displayed correctly in the device manager, everything seems to work well, except for Parsec, which gives an error when trying to connect.

Still no way to fix this?

**Comment by darkman7hr** [comment]
bump. still here, All polaris cards
